name:   BSN Backend API pipeline
on:
  push:
    branches:
      - ci/pipeline
    paths:
      - BookApp/**
      - docker-compose.yml
      - github/workflows/*-backend.yml

jobs:
  compile:
    runs-on: ubuntu
    name: Compile project

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup JDK
      uses: actions/setup-jdk@v4
      with:
          java-version: 23
          distribution: 'amazoncorretto'

    - name: Compile project
      run:
        ./mvnw clean compile



build:

    runs-on: ubuntu
    name: Build Backend project
    needs: [compile]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-jdk@v4
        with:
          java-version: 23
          distribution: 'amazoncorretto'

      - name: Compile project
        run:
          ./mvnw clean package


build-image:
  name: build Docker image
  runs-on: ubuntu
  needs: [build]

  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup JDK
      uses: actions/setup-jdk@v4
      with:
        java-version: 23
        distribution: 'amazoncorretto'
    - name: Extract project version
      id: extract_version
      run:
        echo "VERSION=$(./mvnw -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec)" >> GITHUB_OUTPUT

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: Build & push to DockerHub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true







